name: Runner Workflow

on:
 push

jobs:
  linux:
     runs-on: ubuntu-latest
     steps:
     - name: linux
       run: |
         echo " This job is running on a ubuntu runner"
         echo " Runner OS is $RUNNER_OS"
