name: Runner Workflow

on:
 push

jobs:
  linux:
     runs-on: ubuntu-latest
     steps:
     - name: linux
       run: |
         echo " This job is running on a ubuntu runner"
         echo " Runner OS is $RUNNER_OS"
   windows:
     runs-on: windows-latet
     steps:
     - name: windows
       shell: bash
       run: |
         echo " This job is running on a windows runner"
         echo " Runner OS is $RUNNER_OS"
    mac:
     runs-on: mac-latet
     steps:
     - name: mac
       shell: bash
       run: |
         echo " This job is running on a macrunner"
         echo " Runner OS is $RUNNER_OS"
    
        

         
